### ISSUE TITLE
Request: more customization options for moveTo and walking animations

### ISSUE THREAD

**Issue by DouglasDev** [Annoraaq/grid-engine#119]
Hi, overall excellent library. There are two features that I need to complete my game. If you can point me in the right direction, I would be willing to add the features myself. The features are:
1. An observable or event listener that is triggered when the character arrives at the destination and also one that is triggered when their path is completely blocked.
2. A way to better sync the animations with moveTo. The problem I'm having is that my walking animation has 6 frames but since the movementStarted observable is triggered on every tile, only the first 3 frames play, resulting in a jerky animation. I had an idea to only restart the animation if the character's direction changes, however there is no way to know when to stop the animation without first implementing feature #1.

One other feature that would be nice, but not required is to be able to use moveTo with a Tiled object. I figured out a workaround by dividing the xy coordinates of the object by the tile size and rounding down, but this doesn't seem like a very elegant solution.

Thanks!

**Comment by Annoraaq** [comment]
Hi @DouglasDev,

thank you for your input. These are really good suggestions.

## Point 1:
 ### Observable 'when the character arrives at the destination':
 This can be accomplished by using the existing observable `positionChanged()` or `positionChangFinished()`. By using rxjs you can [filter](https://www.learnrxjs.io/learn-rxjs/operators/filtering/filter) that observable by the character and tile you want to move to. However, we could add this as an additional observable within the plugin as a shorthand, so it is easier to use.
 
  ### Observable 'path is completely blocked':
 What do you mean by "completely blocked"? Do you mean that there does not exist any path from the char to the target anymore? My next question would be how often that observable should fire, because the state of being blocked may or may not hold on forever. Imagine a map where there is simply no path because the char is on an island or something. Then it would stay blocked and the observable would fire a lot (bad performance). In other cases the path might only be temporarily blocked by another character that is currently blocking the only path. Because of this issues, there might be a better way to achieve, what you want to achieve by using this observable.

In fact, I am currently working on extending moveTo with strategies for those cases. You can then pass a strategy for a 'no path found scenario' and a 'current path blocked' scenario. A **'no path found'** scenario means that at the moment you are calling moveTo there does not exist a path to the target. 3 possible strategies would be **'retry'**, **'stop'**, **'closest reachable point'**. **'retry'** would simply try again on every update, **'stop'** would cancel the moveTo. **'closest reachable'** will instead choose the closest point to the target, that is reachable.

A **'current path blocked'** scenario is the case when moveTo found a path and started moving the char. Then on the way the path is suddenly blocked (i.e. by some other char). Then there are also 3 possible strategies (and probably many more): **'stop'**, **'wait'** and **'retry'**. **'stop'** will cancel the moveTo movement. **'wait'** will simply wait (possibly forever) until the path gets unblocked again. **'retry'** will look for a new path to the target.

Maybe these will already help you?

## Point 2:

> since the movementStarted observable is triggered on every tile
I could not reproduce this. If this is the case, it is definitively a bug. I checked by taking the code of this example: https://annoraaq.github.io/grid-engine/examples/custom-walking-animation.html and call moveTo on the player. Then I put a console.log into the subscription function of the movementStarted observable.

It only fires on a change of direction or if the character was not moving before. So if the player walks 5 tiles into the same direction, the observable should only fire once. 

If this is not the case for you, please provide more information, so I can reproduce the bug and fix it.

## Point 3:
I did not use Tiled objects before but as far as I know their position is pixel based and not tile based.
It feels to me like an anti-pattern to use pixel positioned objects in a tile based physics world. Moreover, there is not a single strategy to define the tile position of a pixel based object of a random shape. Therefore I would rather leave this to the logic of the game that uses gridEngine and not gridEngine itself. 

But on the roadmap are features that will allow to place invisible objects to tiles so you can interact with them. You can achieve this already by adding invisible fake-characters to gridEngine. But it is quite hacky.

**Comment by Annoraaq** [comment]
>  I need a way for the character to "give up" and stop trying to move to the target if the path is blocked. 

This will be possible soon with my mentioned strategy settings. However, your case sounds a bit like you could need an option that is like: "if the path is blocked, try to find a new one for some amount of time and if that fails, give up". I think I will add that to the possible strategies.

> A way to distinguish between temporarily and permanently blocked paths would also be great.

I fear this is not possible in general. However, under the assumptions that the "blocking" property of a tile in the tilemap does never change, it would be possible to at least in this case detect that the path is blocked and will never be unblocked again. If there is a "moving object" like a character that is blocking, it COULD change in the future but there is still no guarantee. So this method will not be 100% accurate. Like mentioned above I could introduce something like a timeout or a max_retry configuration value.

> Perhaps you know of a way to accomplish this without objects?

This depends a bit on where you want to add these items. If you want to add them in Tiled, then I don't know another method.

If you don't insist on keeping this information in the tilemap, then there are lots of possibilities to achieve that. One would be to keep a list of game objects like buttons and their tile coordinates in some data structure and with the observables of the plugin you can check if the char is standing on one of them.

If you need to move those or make them collidable you can add them as "characters" to the plugin (even though they won't be real characters). But I am planning a better support for non-character objects in the future.

**Comment by DouglasDev** [comment]
My minimal example for reproducing the bug is this:
`import Phaser from 'phaser'
import { GridEngine } from 'grid-engine'

var game = new Phaser.Game({
  type: Phaser.AUTO,
  width: 400,
  height: 300,
  scene: {
    preload,
    create,
  },
  scale: {
    autoCenter: Phaser.Scale.CENTER_HORIZONTALLY,
  },
  plugins: {
    scene: [
      {
        key: 'gridEngine',
        plugin: GridEngine,
        mapping: 'gridEngine',
      },
    ],
  },
})

function preload() {
  this.load.image('1_Generic_16x16', './1_Generic_16x16.png')
  this.load.tilemapTiledJSON('tilemap', './map1.json')
  this.load.spritesheet('player', './Alex_run_16x16.png', {
    frameWidth: 16,
    frameHeight: 32,
  })
}

function createPlayerAnimation(name, startFrame, endFrame) {
  this.anims.create({
    key: name,
    frames: this.anims.generateFrameNumbers('player', {
      start: startFrame,
      end: endFrame,
    }),
    frameRate: 10,
    repeat: -1,
  })
}
function getStopFrame(direction) {
  switch (direction) {
    case 'right':
      return 5
    case 'up':
      return 11
    case 'left':
      return 17
    case 'down':
      return 23
  }
}

function create() {
  const map = this.make.tilemap({ key: 'tilemap' })
  const tileset = map.addTilesetImage('1_Generic_16x16')

  map.createLayer('ground', tileset)
  map.createLayer('middle', tileset)
  map.createLayer('middle-above', tileset)

  const playerSprite = this.add.sprite(20, 20, 'player')
  this.cameras.main.startFollow(playerSprite, true)
  this.cameras.main.setFollowOffset(-playerSprite.width, -playerSprite.height)

  createPlayerAnimation.call(this, 'right', 0, 5)
  createPlayerAnimation.call(this, 'up', 6, 11)
  createPlayerAnimation.call(this, 'left', 12, 17)
  createPlayerAnimation.call(this, 'down', 18, 23)

  const gridEngineConfig = {
    characters: [
      {
        id: 'player',
        sprite: playerSprite,
        walkingAnimationEnabled: false,
        startPosition: new Phaser.Math.Vector2(10,10),
      },
    ],
  }

  this.gridEngine.create(map, gridEngineConfig)

  playerSprite.setFrame(getStopFrame('down'))

  this.gridEngine.movementStarted().subscribe(([_charId, direction]) => {
    console.log('started')
    playerSprite.anims.play(direction)
  })

  this.gridEngine.movementStopped().subscribe(([_charId, direction]) => {
    console.log('stopped')
    playerSprite.anims.stop()
    playerSprite.setFrame(getStopFrame(direction))
  })

  this.gridEngine.directionChanged().subscribe(([_charId, direction]) => {
    console.log('directionChanged')
    playerSprite.setFrame(getStopFrame(direction))
  })
  this.gridEngine.moveTo('player', new Phaser.Math.Vector2(1, 1))
}
`

The tilemap shouldn't matter so you can use anything for that. This is the character sprite sheet:
![Adam_run_16x16](https://user-images.githubusercontent.com/25951701/117895281-042aa000-b28c-11eb-9984-f4d090dfc124.png)

You should see it log "started" and "stopped" every 3 frames, and "directionChanged" will never get logged. Please let me know if you need any other info. Thanks.

**Comment by DouglasDev** [comment]
Also I really like your idea for setting a timeout for when the character will give up if the path is block and I think it would work well with my use case.

**Comment by DouglasDev** [comment]
One other issue I noticed:
when I add the following code:
```
  this.gridEngine.positionChanged().subscribe(([_charId, exitTile,enterTile]) => {
    console.log('positionChanged',exitTile,enterTile)
  })
```
 to the create function in the example above, I get the error:
```
Uncaught TypeError: undefined is not a function
    at T._next (phaserApp.js:99)
    at T.__tryOrUnsub (grid-engine.js:53)
    at T.next (grid-engine.js:53)
    at T._next (grid-engine.js:53)
    at T.next (grid-engine.js:53)
    at T.next (grid-engine.js:53)
    at T._next (grid-engine.js:53)
    at T.__tryOrUnsub (grid-engine.js:53)
    at T.next (grid-engine.js:53)
    at T._next (grid-engine.js:53)
```

not sure if it's a bug or if I'm misusing the observable somehow.

**Comment by Annoraaq** [comment]
Hey @DouglasDev 
I will try to reproduce the bug with moveTo and keep you up to date. Thank you for the detailed information.

Regarding your other issue with the observable. You have to destructure it as an object:
`subscribe(({charId, exitTile, enterTile})` vs `subscribe(([_charId, exitTile,enterTile])`.
In your particular case where you don't use the charId you can do: `subscribe(({exitTile, enterTile})`.

I must admit that it is a bit incosistent that some observables return arrays while others return objects. I like objects more, because the have semantics. But for some reason I did use arrays for the early observables and I kept them like this to stay backwards compatible.

**Comment by Annoraaq** [comment]
@DouglasDev

You are right. It is a bug and it was introduced with 1.14.1 but the examples are still using 1.14.0. That is how I could not reproduce it. Thank you for your help!

I will fix create a bug and fix it with the next update that will also bring other changes for moveTo.

**Comment by Annoraaq** [comment]
@DouglasDev fyi:
The bug that caused the movementStarted observable to fire on every tile has been resolved with 1.15.0.
Also you can find `moveTo` to be more configurable already. However, there are still some strategies missing (also the timeout). I created issues for those: #123, #124, #125 
You can track the features there.

**Comment by DouglasDev** [comment]
Thanks so much!

**Comment by DouglasDev** [comment]
Hi, I didn't have time until now to try out the new version. I installed version 1.15.0 and tested it with my example above and I'm still having the issue where movementStarted and movementStopped are fired on every tile. When you retest it you didn't have that happen? Is 1.15.0 the correct version?

**Comment by Annoraaq** [comment]
Yes, version 1.15.0 is the correct one. See this example here that uses a custom animation and also calls console.log for every movementStarted:
https://codesandbox.io/s/dank-sun-4vj7x?file=/src/index.js

**Comment by DouglasDev** [comment]
In your example, I'm still seeing movementStarted and movementStopped called every time the character changes direction, and directionChanged is never called. Are you saying this is the correct behavior? I was expecting that movementStarted would only be called once when the player starts moving, directionChanged would be called each time the direction changes and movementStopped only called after the character stops completely.

Also, In my example, movementStarted is still being called on each tile. I will try to figure out why it's behaving differently that your example.

Anyway, thanks for all of your help.

**Comment by DouglasDev** [comment]
I just notice another small issue: if your use the keyboard controls and move the player to a wall and keep holding down the arrow key in the direction of the wall, directionChanged is called on every single frame.

**Comment by Annoraaq** [comment]
Yes, that is the intended behavior. These observables were introduced for exactly your use case. So movementStarted and movementStopped are called every time you typically want to start a movement animation.

DirectionChanged is for changing direction without moving. The docs describe it like:

> Returns an Observable that will notify about every change of direction that **is not part of a movement**. This is the case if the character tries to walk towards a blocked tile. The character will turn but not move.

This is necessary in order to set the correct character frame for a custom animation.

I hope this helps. Maybe I should be more precise about movementStarted and movementStopped in the docs.

I will try to reproduce the bug with your example from above again with 1.15.0. Have you made sure that your browser was not caching and old version of GridEngine?

**Comment by DouglasDev** [comment]
Okay thanks for the explanation. Yes, you were correct that it was an old version so no need to reproduce it. Somehow deleting my node_modules and reinstalling fixed it. Have a good rest of your weekend!

**Comment by Annoraaq** [comment]
Thanks. You, too! Glad it works now 🙂
